name: validate Fabric schemas

on:
  pull_request:
    paths:
      - 'fabric/**/*.json'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Setup Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run tests
        run: |
          pytest ./tests/validate-fabric-schemas_test.py